### ISSUE TITLE
what are the values in the array RETSPL

### ISSUE THREAD

**Issue by ygliboch** [Kash2610/Hearing-Impaired-Test--HIT-#1]
Hello!
I'm trying to figure out with your example how sound is generated for hearing tests. and the only thing I can't figure out right now is where did you get such an array
```
var RETSPL: [Float] = [1.8, -0.5, -0.6, 2.2, 0, 5.1, 6.7, 13.2, 11.2]
```
this array is used in the method:
```
func getVol (indB: Int) -> Float {
         let vol_spl = Float (indB) + (RETSPL [Index_Hz])
         let vol_FS = vol_spl - Float (dBSPL_MAX [Index_Hz])
         let vol = pow (10, vol_FS / 20)
         print ("Vol SPL is:", vol_spl, "vol FS is:", vol_FS, "vol is:", vol, "Index is:", Index_Hz)
         return vol
 }
```
your answer will help me a lot!

**Comment by Kash2610** [comment]
Hi,

The RETSPL stands for Reference Equivalent Threshold Sound Pressure Level.
It is a calibration term used to measure the sound output level coming
through the smartphone and earphone pair used. It was derived empirically
based on clinical trials hence you did not found any proof there.

The values might change when changing the earphone or smartphone. In our
case, we have used iPhone 11 with Sennheiser CX 300 earphones and achieved
good results.

I am glad that the project is useful to you!

Let me know if you have any other doubts.

Thanks,
Kashyap Patel

**Comment by Kash2610** [comment]
> Hello!
> I'm trying to figure out with your example how sound is generated for hearing tests. and the only thing I can't figure out right now is where did you get such an array
> 
> ```
> var RETSPL: [Float] = [1.8, -0.5, -0.6, 2.2, 0, 5.1, 6.7, 13.2, 11.2]
> ```
> 
> this array is used in the method:
> 
> ```
> func getVol (indB: Int) -> Float {
>          let vol_spl = Float (indB) + (RETSPL [Index_Hz])
>          let vol_FS = vol_spl - Float (dBSPL_MAX [Index_Hz])
>          let vol = pow (10, vol_FS / 20)
>          print ("Vol SPL is:", vol_spl, "vol FS is:", vol_FS, "vol is:", vol, "Index is:", Index_Hz)
>          return vol
>  }
> ```
> 
> your answer will help me a lot!

Hi, I have emailed your query regarding the RETSPL values. 

One more thing, the sound is not generated in the application. You can store and use the pre-generated sound files. In my case, I use sine waves of different frequencies through MATLAB first.

**Comment by ygliboch** [comment]
Kashyap Patel, thanks for your answer, it helped me)
